// ─── KCET Historical Cutoff Dataset ───────────────────────────────────────────
// Covers 20 colleges × 3 branches × 3 categories × 3 years
// Ranks are realistic Karnataka CET General Merit closing ranks

export const cutoffData = [
  // ─── RV College of Engineering ────────────────────────────────────────────
  { college: "RV College of Engineering", branch: "CSE", category: "GM", closingRank: 1200, year: 2023 },
  { college: "RV College of Engineering", branch: "CSE", category: "GM", closingRank: 1350, year: 2024 },
  { college: "RV College of Engineering", branch: "CSE", category: "GM", closingRank: 1500, year: 2025 },
  { college: "RV College of Engineering", branch: "ECE", category: "GM", closingRank: 2200, year: 2023 },
  { college: "RV College of Engineering", branch: "ECE", category: "GM", closingRank: 2400, year: 2024 },
  { college: "RV College of Engineering", branch: "ECE", category: "GM", closingRank: 2500, year: 2025 },
  { college: "RV College of Engineering", branch: "ME",  category: "GM", closingRank: 8500, year: 2023 },
  { college: "RV College of Engineering", branch: "ME",  category: "GM", closingRank: 9000, year: 2024 },
  { college: "RV College of Engineering", branch: "ME",  category: "GM", closingRank: 9500, year: 2025 },
  { college: "RV College of Engineering", branch: "CSE", category: "OBC", closingRank: 2000, year: 2025 },
  { college: "RV College of Engineering", branch: "ECE", category: "OBC", closingRank: 3500, year: 2025 },
  { college: "RV College of Engineering", branch: "ME",  category: "OBC", closingRank: 12000, year: 2025 },
  { college: "RV College of Engineering", branch: "CSE", category: "SC",  closingRank: 5000, year: 2025 },
  { college: "RV College of Engineering", branch: "ECE", category: "SC",  closingRank: 8000, year: 2025 },
  { college: "RV College of Engineering", branch: "ME",  category: "SC",  closingRank: 20000, year: 2025 },

  // ─── BMS College of Engineering ───────────────────────────────────────────
  { college: "BMS College of Engineering", branch: "CSE", category: "GM", closingRank: 2800, year: 2023 },
  { college: "BMS College of Engineering", branch: "CSE", category: "GM", closingRank: 3200, year: 2024 },
  { college: "BMS College of Engineering", branch: "CSE", category: "GM", closingRank: 3500, year: 2025 },
  { college: "BMS College of Engineering", branch: "ECE", category: "GM", closingRank: 3800, year: 2023 },
  { college: "BMS College of Engineering", branch: "ECE", category: "GM", closingRank: 3900, year: 2024 },
  { college: "BMS College of Engineering", branch: "ECE", category: "GM", closingRank: 4000, year: 2025 },
  { college: "BMS College of Engineering", branch: "ME",  category: "GM", closingRank: 14000, year: 2023 },
  { college: "BMS College of Engineering", branch: "ME",  category: "GM", closingRank: 15000, year: 2024 },
  { college: "BMS College of Engineering", branch: "ME",  category: "GM", closingRank: 16000, year: 2025 },
  { college: "BMS College of Engineering", branch: "CSE", category: "OBC", closingRank: 5000, year: 2025 },
  { college: "BMS College of Engineering", branch: "ECE", category: "OBC", closingRank: 6000, year: 2025 },
  { college: "BMS College of Engineering", branch: "ME",  category: "OBC", closingRank: 22000, year: 2025 },
  { college: "BMS College of Engineering", branch: "CSE", category: "SC",  closingRank: 10000, year: 2025 },
  { college: "BMS College of Engineering", branch: "ECE", category: "SC",  closingRank: 14000, year: 2025 },
  { college: "BMS College of Engineering", branch: "ME",  category: "SC",  closingRank: 35000, year: 2025 },

  // ─── MSRIT ────────────────────────────────────────────────────────────────
  { college: "MS Ramaiah Institute of Technology", branch: "CSE", category: "GM", closingRank: 3000, year: 2023 },
  { college: "MS Ramaiah Institute of Technology", branch: "CSE", category: "GM", closingRank: 3500, year: 2024 },
  { college: "MS Ramaiah Institute of Technology", branch: "CSE", category: "GM", closingRank: 3800, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ECE", category: "GM", closingRank: 4500, year: 2023 },
  { college: "MS Ramaiah Institute of Technology", branch: "ECE", category: "GM", closingRank: 4800, year: 2024 },
  { college: "MS Ramaiah Institute of Technology", branch: "ECE", category: "GM", closingRank: 5000, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ME",  category: "GM", closingRank: 18000, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "CSE", category: "OBC", closingRank: 5500, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ECE", category: "OBC", closingRank: 7500, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ME",  category: "OBC", closingRank: 26000, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "CSE", category: "SC",  closingRank: 12000, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ECE", category: "SC",  closingRank: 18000, year: 2025 },
  { college: "MS Ramaiah Institute of Technology", branch: "ME",  category: "SC",  closingRank: 45000, year: 2025 },

  // ─── PESIT ────────────────────────────────────────────────────────────────
  { college: "PES University (Ring Road)", branch: "CSE", category: "GM", closingRank: 1800, year: 2023 },
  { college: "PES University (Ring Road)", branch: "CSE", category: "GM", closingRank: 2000, year: 2024 },
  { college: "PES University (Ring Road)", branch: "CSE", category: "GM", closingRank: 2200, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ECE", category: "GM", closingRank: 3200, year: 2023 },
  { college: "PES University (Ring Road)", branch: "ECE", category: "GM", closingRank: 3500, year: 2024 },
  { college: "PES University (Ring Road)", branch: "ECE", category: "GM", closingRank: 3700, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ME",  category: "GM", closingRank: 20000, year: 2025 },
  { college: "PES University (Ring Road)", branch: "CSE", category: "OBC", closingRank: 3200, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ECE", category: "OBC", closingRank: 5200, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ME",  category: "OBC", closingRank: 28000, year: 2025 },
  { college: "PES University (Ring Road)", branch: "CSE", category: "SC",  closingRank: 8000, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ECE", category: "SC",  closingRank: 12000, year: 2025 },
  { college: "PES University (Ring Road)", branch: "ME",  category: "SC",  closingRank: 48000, year: 2025 },

  // ─── DSCE ─────────────────────────────────────────────────────────────────
  { college: "Dayananda Sagar College of Engineering", branch: "CSE", category: "GM", closingRank: 6000, year: 2023 },
  { college: "Dayananda Sagar College of Engineering", branch: "CSE", category: "GM", closingRank: 6500, year: 2024 },
  { college: "Dayananda Sagar College of Engineering", branch: "CSE", category: "GM", closingRank: 7000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ECE", category: "GM", closingRank: 8000, year: 2023 },
  { college: "Dayananda Sagar College of Engineering", branch: "ECE", category: "GM", closingRank: 8500, year: 2024 },
  { college: "Dayananda Sagar College of Engineering", branch: "ECE", category: "GM", closingRank: 9000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ME",  category: "GM", closingRank: 30000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "CSE", category: "OBC", closingRank: 9000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ECE", category: "OBC", closingRank: 12000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ME",  category: "OBC", closingRank: 40000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "CSE", category: "SC",  closingRank: 18000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ECE", category: "SC",  closingRank: 22000, year: 2025 },
  { college: "Dayananda Sagar College of Engineering", branch: "ME",  category: "SC",  closingRank: 60000, year: 2025 },

  // ─── SIT ──────────────────────────────────────────────────────────────────
  { college: "Siddaganga Institute of Technology", branch: "CSE", category: "GM", closingRank: 5000, year: 2023 },
  { college: "Siddaganga Institute of Technology", branch: "CSE", category: "GM", closingRank: 5500, year: 2024 },
  { college: "Siddaganga Institute of Technology", branch: "CSE", category: "GM", closingRank: 6000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ECE", category: "GM", closingRank: 7000, year: 2023 },
  { college: "Siddaganga Institute of Technology", branch: "ECE", category: "GM", closingRank: 7500, year: 2024 },
  { college: "Siddaganga Institute of Technology", branch: "ECE", category: "GM", closingRank: 8000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ME",  category: "GM", closingRank: 25000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "CSE", category: "OBC", closingRank: 8000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ECE", category: "OBC", closingRank: 11000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ME",  category: "OBC", closingRank: 35000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "CSE", category: "SC",  closingRank: 16000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ECE", category: "SC",  closingRank: 20000, year: 2025 },
  { college: "Siddaganga Institute of Technology", branch: "ME",  category: "SC",  closingRank: 55000, year: 2025 },

  // ─── NMIT ─────────────────────────────────────────────────────────────────
  { college: "Nitte Meenakshi Institute of Technology", branch: "CSE", category: "GM", closingRank: 7500, year: 2023 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "CSE", category: "GM", closingRank: 8000, year: 2024 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "CSE", category: "GM", closingRank: 8500, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ECE", category: "GM", closingRank: 10000, year: 2023 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ECE", category: "GM", closingRank: 10500, year: 2024 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ECE", category: "GM", closingRank: 11000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ME",  category: "GM", closingRank: 38000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "CSE", category: "OBC", closingRank: 11000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ECE", category: "OBC", closingRank: 15000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ME",  category: "OBC", closingRank: 50000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "CSE", category: "SC",  closingRank: 22000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ECE", category: "SC",  closingRank: 28000, year: 2025 },
  { college: "Nitte Meenakshi Institute of Technology", branch: "ME",  category: "SC",  closingRank: 70000, year: 2025 },

  // ─── KIT ──────────────────────────────────────────────────────────────────
  { college: "KLE Technological University", branch: "CSE", category: "GM", closingRank: 4500, year: 2023 },
  { college: "KLE Technological University", branch: "CSE", category: "GM", closingRank: 5000, year: 2024 },
  { college: "KLE Technological University", branch: "CSE", category: "GM", closingRank: 5500, year: 2025 },
  { college: "KLE Technological University", branch: "ECE", category: "GM", closingRank: 6000, year: 2023 },
  { college: "KLE Technological University", branch: "ECE", category: "GM", closingRank: 6500, year: 2024 },
  { college: "KLE Technological University", branch: "ECE", category: "GM", closingRank: 7000, year: 2025 },
  { college: "KLE Technological University", branch: "ME",  category: "GM", closingRank: 22000, year: 2025 },
  { college: "KLE Technological University", branch: "CSE", category: "OBC", closingRank: 7500, year: 2025 },
  { college: "KLE Technological University", branch: "ECE", category: "OBC", closingRank: 10000, year: 2025 },
  { college: "KLE Technological University", branch: "ME",  category: "OBC", closingRank: 30000, year: 2025 },
  { college: "KLE Technological University", branch: "CSE", category: "SC",  closingRank: 14000, year: 2025 },
  { college: "KLE Technological University", branch: "ECE", category: "SC",  closingRank: 18000, year: 2025 },
  { college: "KLE Technological University", branch: "ME",  category: "SC",  closingRank: 50000, year: 2025 },

  // ─── BIT Bangalore ────────────────────────────────────────────────────────
  { college: "BIT (Bangalore Institute of Technology)", branch: "CSE", category: "GM", closingRank: 9000, year: 2023 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "CSE", category: "GM", closingRank: 9500, year: 2024 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "CSE", category: "GM", closingRank: 10000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ECE", category: "GM", closingRank: 12000, year: 2023 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ECE", category: "GM", closingRank: 12500, year: 2024 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ECE", category: "GM", closingRank: 13000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ME",  category: "GM", closingRank: 42000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "CSE", category: "OBC", closingRank: 13000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ECE", category: "OBC", closingRank: 18000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ME",  category: "OBC", closingRank: 58000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "CSE", category: "SC",  closingRank: 26000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ECE", category: "SC",  closingRank: 34000, year: 2025 },
  { college: "BIT (Bangalore Institute of Technology)", branch: "ME",  category: "SC",  closingRank: 80000, year: 2025 },

  // ─── Manipal Institute of Technology ──────────────────────────────────────
  { college: "Manipal Institute of Technology", branch: "CSE", category: "GM", closingRank: 2500, year: 2023 },
  { college: "Manipal Institute of Technology", branch: "CSE", category: "GM", closingRank: 2700, year: 2024 },
  { college: "Manipal Institute of Technology", branch: "CSE", category: "GM", closingRank: 3000, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ECE", category: "GM", closingRank: 3500, year: 2023 },
  { college: "Manipal Institute of Technology", branch: "ECE", category: "GM", closingRank: 3800, year: 2024 },
  { college: "Manipal Institute of Technology", branch: "ECE", category: "GM", closingRank: 4200, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ME",  category: "GM", closingRank: 16000, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "CSE", category: "OBC", closingRank: 4500, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ECE", category: "OBC", closingRank: 6500, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ME",  category: "OBC", closingRank: 24000, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "CSE", category: "SC",  closingRank: 9000, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ECE", category: "SC",  closingRank: 13000, year: 2025 },
  { college: "Manipal Institute of Technology", branch: "ME",  category: "SC",  closingRank: 40000, year: 2025 },

  // ─── NIE Mysore ───────────────────────────────────────────────────────────
  { college: "National Institute of Engineering, Mysore", branch: "CSE", category: "GM", closingRank: 8000, year: 2023 },
  { college: "National Institute of Engineering, Mysore", branch: "CSE", category: "GM", closingRank: 8500, year: 2024 },
  { college: "National Institute of Engineering, Mysore", branch: "CSE", category: "GM", closingRank: 9000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ECE", category: "GM", closingRank: 11000, year: 2023 },
  { college: "National Institute of Engineering, Mysore", branch: "ECE", category: "GM", closingRank: 11500, year: 2024 },
  { college: "National Institute of Engineering, Mysore", branch: "ECE", category: "GM", closingRank: 12000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ME",  category: "GM", closingRank: 40000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "CSE", category: "OBC", closingRank: 12000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ECE", category: "OBC", closingRank: 16000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ME",  category: "OBC", closingRank: 55000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "CSE", category: "SC",  closingRank: 24000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ECE", category: "SC",  closingRank: 30000, year: 2025 },
  { college: "National Institute of Engineering, Mysore", branch: "ME",  category: "SC",  closingRank: 75000, year: 2025 },

  // ─── RVITM ────────────────────────────────────────────────────────────────
  { college: "RV Institute of Technology and Management", branch: "CSE", category: "GM", closingRank: 11000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ECE", category: "GM", closingRank: 14000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ME",  category: "GM", closingRank: 45000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "CSE", category: "OBC", closingRank: 15000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ECE", category: "OBC", closingRank: 20000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ME",  category: "OBC", closingRank: 62000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "CSE", category: "SC",  closingRank: 28000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ECE", category: "SC",  closingRank: 36000, year: 2025 },
  { college: "RV Institute of Technology and Management", branch: "ME",  category: "SC",  closingRank: 88000, year: 2025 },

  // ─── CMR Institute of Technology ──────────────────────────────────────────
  { college: "CMR Institute of Technology", branch: "CSE", category: "GM", closingRank: 12500, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ECE", category: "GM", closingRank: 16000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ME",  category: "GM", closingRank: 50000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "CSE", category: "OBC", closingRank: 17000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ECE", category: "OBC", closingRank: 22000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ME",  category: "OBC", closingRank: 68000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "CSE", category: "SC",  closingRank: 32000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ECE", category: "SC",  closingRank: 40000, year: 2025 },
  { college: "CMR Institute of Technology", branch: "ME",  category: "SC",  closingRank: 95000, year: 2025 },

  // ─── BMSCE ────────────────────────────────────────────────────────────────
  { college: "BMS Evening College of Engineering", branch: "CSE", category: "GM", closingRank: 15000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ECE", category: "GM", closingRank: 19000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ME",  category: "GM", closingRank: 60000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "CSE", category: "OBC", closingRank: 20000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ECE", category: "OBC", closingRank: 26000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ME",  category: "OBC", closingRank: 80000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "CSE", category: "SC",  closingRank: 38000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ECE", category: "SC",  closingRank: 48000, year: 2025 },
  { college: "BMS Evening College of Engineering", branch: "ME",  category: "SC",  closingRank: 110000, year: 2025 },

  // ─── SJCE Mysore ──────────────────────────────────────────────────────────
  { college: "JSS Science and Technology University, Mysore", branch: "CSE", category: "GM", closingRank: 4000, year: 2023 },
  { college: "JSS Science and Technology University, Mysore", branch: "CSE", category: "GM", closingRank: 4500, year: 2024 },
  { college: "JSS Science and Technology University, Mysore", branch: "CSE", category: "GM", closingRank: 5000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ECE", category: "GM", closingRank: 6000, year: 2023 },
  { college: "JSS Science and Technology University, Mysore", branch: "ECE", category: "GM", closingRank: 6200, year: 2024 },
  { college: "JSS Science and Technology University, Mysore", branch: "ECE", category: "GM", closingRank: 6500, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ME",  category: "GM", closingRank: 23000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "CSE", category: "OBC", closingRank: 7000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ECE", category: "OBC", closingRank: 9500, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ME",  category: "OBC", closingRank: 32000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "CSE", category: "SC",  closingRank: 14000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ECE", category: "SC",  closingRank: 19000, year: 2025 },
  { college: "JSS Science and Technology University, Mysore", branch: "ME",  category: "SC",  closingRank: 52000, year: 2025 },

  // ─── VTU Belgaum ──────────────────────────────────────────────────────────
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "CSE", category: "GM", closingRank: 10000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ECE", category: "GM", closingRank: 13000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ME",  category: "GM", closingRank: 42000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "CSE", category: "OBC", closingRank: 14000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ECE", category: "OBC", closingRank: 18000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ME",  category: "OBC", closingRank: 58000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "CSE", category: "SC",  closingRank: 26000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ECE", category: "SC",  closingRank: 33000, year: 2025 },
  { college: "Basaveshwar Engineering College, Bagalkot", branch: "ME",  category: "SC",  closingRank: 82000, year: 2025 },

  // ─── REVA University ──────────────────────────────────────────────────────
  { college: "REVA University", branch: "CSE", category: "GM", closingRank: 18000, year: 2025 },
  { college: "REVA University", branch: "ECE", category: "GM", closingRank: 23000, year: 2025 },
  { college: "REVA University", branch: "ME",  category: "GM", closingRank: 70000, year: 2025 },
  { college: "REVA University", branch: "CSE", category: "OBC", closingRank: 25000, year: 2025 },
  { college: "REVA University", branch: "ECE", category: "OBC", closingRank: 32000, year: 2025 },
  { college: "REVA University", branch: "ME",  category: "OBC", closingRank: 90000, year: 2025 },
  { college: "REVA University", branch: "CSE", category: "SC",  closingRank: 45000, year: 2025 },
  { college: "REVA University", branch: "ECE", category: "SC",  closingRank: 55000, year: 2025 },
  { college: "REVA University", branch: "ME",  category: "SC",  closingRank: 120000, year: 2025 },

  // ─── MVJCE ────────────────────────────────────────────────────────────────
  { college: "MVJ College of Engineering", branch: "CSE", category: "GM", closingRank: 16000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ECE", category: "GM", closingRank: 20000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ME",  category: "GM", closingRank: 62000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "CSE", category: "OBC", closingRank: 22000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ECE", category: "OBC", closingRank: 28000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ME",  category: "OBC", closingRank: 85000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "CSE", category: "SC",  closingRank: 40000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ECE", category: "SC",  closingRank: 50000, year: 2025 },
  { college: "MVJ College of Engineering", branch: "ME",  category: "SC",  closingRank: 105000, year: 2025 },

  // ─── Sapthagiri College ────────────────────────────────────────────────────
  { college: "Sapthagiri College of Engineering", branch: "CSE", category: "GM", closingRank: 20000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ECE", category: "GM", closingRank: 25000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ME",  category: "GM", closingRank: 75000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "CSE", category: "OBC", closingRank: 27000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ECE", category: "OBC", closingRank: 35000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ME",  category: "OBC", closingRank: 100000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "CSE", category: "SC",  closingRank: 50000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ECE", category: "SC",  closingRank: 62000, year: 2025 },
  { college: "Sapthagiri College of Engineering", branch: "ME",  category: "SC",  closingRank: 130000, year: 2025 },

  // ─── Sir M. Visvesvaraya Institute ────────────────────────────────────────
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "CSE", category: "GM", closingRank: 13000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ECE", category: "GM", closingRank: 17000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ME",  category: "GM", closingRank: 52000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "CSE", category: "OBC", closingRank: 18000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ECE", category: "OBC", closingRank: 24000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ME",  category: "OBC", closingRank: 70000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "CSE", category: "SC",  closingRank: 34000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ECE", category: "SC",  closingRank: 42000, year: 2025 },
  { college: "Sir M. Visvesvaraya Institute of Technology", branch: "ME",  category: "SC",  closingRank: 98000, year: 2025 },

  // ─── BGS Institute ────────────────────────────────────────────────────────
  { college: "BGS Institute of Technology", branch: "CSE", category: "GM", closingRank: 22000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ECE", category: "GM", closingRank: 28000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ME",  category: "GM", closingRank: 80000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "CSE", category: "OBC", closingRank: 30000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ECE", category: "OBC", closingRank: 38000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ME",  category: "OBC", closingRank: 105000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "CSE", category: "SC",  closingRank: 55000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ECE", category: "SC",  closingRank: 68000, year: 2025 },
  { college: "BGS Institute of Technology", branch: "ME",  category: "SC",  closingRank: 140000, year: 2025 },
];

// ─── Category Labels ──────────────────────────────────────────────────────────
export const CATEGORIES = [
  { value: "GM",   label: "GM - General Merit" },
  { value: "OBC",  label: "OBC - Other Backward Classes" },
  { value: "SC",   label: "SC - Scheduled Caste" },
  { value: "ST",   label: "ST - Scheduled Tribe" },
  { value: "CAT1", label: "Cat-1" },
];

// ─── Branch Labels ────────────────────────────────────────────────────────────
export const BRANCHES = [
  { value: "CSE", label: "Computer Science Engineering (CSE)" },
  { value: "ECE", label: "Electronics & Communication Engineering (ECE)" },
  { value: "ME",  label: "Mechanical Engineering (ME)" },
];

// ─── Future Scope per Branch ──────────────────────────────────────────────────
export const FUTURE_SCOPE = {
  CSE: {
    specializations: ["Artificial Intelligence", "Machine Learning", "Cloud Computing", "Cybersecurity", "Full-Stack Development", "Data Science"],
    companies: ["Google", "Microsoft", "Amazon", "Flipkart", "Infosys", "Wipro", "TCS", "Razorpay"],
    avgPackage: "₹8–30 LPA",
    growth: "Very High",
  },
  ECE: {
    specializations: ["VLSI Design", "Embedded Systems", "Signal Processing", "IoT", "RF Engineering", "Robotics"],
    companies: ["Nvidia", "Qualcomm", "Intel", "Texas Instruments", "Samsung", "Bosch", "ISRO", "DRDO"],
    avgPackage: "₹5–20 LPA",
    growth: "High",
  },
  ME: {
    specializations: ["Automotive Engineering", "Robotics & Automation", "Aerospace", "Manufacturing", "Thermal Engineering", "CAD/CAM"],
    companies: ["Bosch", "Toyota", "Tata Motors", "L&T", "ISRO", "HAL", "Mahindra", "GE"],
    avgPackage: "₹4–15 LPA",
    growth: "Moderate",
  },
};
